version: "3.9"
services:
  app:
    image: golang:1.16.5-alpine
    volumes:
      - .:/go/src
    working_dir: /go/src
    command: go run main.go
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
      HOST_PORT: 8080
      HTTP_USER: admin
      HTTP_PASS: admin
    restart: unless-stopped
  redis:
    image: redis:alpine
    restart: unless-stopped
