version: "3.9"
services:
  app:
    image: golang:1.16.5-alpine
    volumes:
      - .:/go/src
    working_dir: /go/src
    command: ash -c 'apk add --no-cache openssl &&
             openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes
             -keyout cert.key -out cert.pem -subj "/CN=example.com" &&
             go build -o app &&
             ./app'
    ports:
      - "443:443"
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
      HOST_PORT: 443
      HTTP_USER: admin
      HTTP_PASS: admin
    restart: unless-stopped
  redis:
    image: redis:alpine
    restart: unless-stopped
