version: "3.8"
services:
  app:
    image: golang:1.16.5-alpine
    volumes:
      - .:/go/src
    working_dir: /go/src
    command: go run main.go
    links:
      - redis
  redis:
    image: redis:alpine
